### ISSUE TITLE
output response to string

### ISSUE THREAD

**Issue by QuirkyTurtle94** [kurtlocker/remote-sync#1]
I've forked this to build an express web UI front end. This has been developed exactly how I want it to, though I don't want to console log the output.
I want the output to be accessible in a string so it can be parsed and  passed into an express websocket.
I've tried to use the perform function as a callback to a parser but all output from the perform method seems to return undefined. Can you help with this?

**Comment by HeavyMedl** [comment]
Hi @ElliotGraham94 ,

Did you take a look at the `stdio` property override? You can redirect the `stdout` to do as you please using a configuration like this:

``` js
// This configuration overrides stdout for every operation
const config = {
 operations : [{ ... },{ ... }],
 stdio : {
  stdout : data => doSomething(data)
 }
}
```

Additionally you can override `stdout` for individual operations using a configuration like so

``` js
// Override the stdout for this particular operation. 
const config = {
 operations : [
  {
    settings : {
     stdio : {
      stdout : data => doSomething(data)
     }
    }
  }
 ]
}
```

Let me know if this helps.

**Comment by QuirkyTurtle94** [comment]
Hi @kurtlocker, thanks for the quick reply!

I've looked into that, but I'm struggling to pipe it to a socket.io emit method. I've managed to use the stdio property override to load the console output into a buffer (if you have anyone else having problems, it's important to either use the .toString() function or set a property of the stdio to use UTF-8 encoding). 

I'll keep plugging away at it! You've done a really nice job with this wrapper, it's a delight to use!

**Comment by QuirkyTurtle94** [comment]
Is there some sort of default that is overriding what I put within the stdout setting? Here's my current config file

``` javascript
/*On new user connection*/
io.on('connection', function(socket){
    console.log('new user connected');/*log new user to node console*/
  socket.emit("info", 'new user connected');/*print new user on client interface*/

  var config = {
      operations : [
          {
              operation : 'download',
              command : 'get "files/test.txt"'
          }
      ],
      user : 'user',
      pw : 'password',
      protocol : 'sftp',
      port: '22',
      host : 'localhost',
      stdio : {
        stdout : data => function(data){
          socket.emit('info', data.toString());
        }
      }
  };
  var client = new RemoteSync(config);
  client.perform(); // Downloads test.txt from localhost ftp
})
```

Nesting the wrapper within the io.socket works fine and any socket commands I put outside of the config work great, but I can't get any functions to compute from within the `stdout: data => function(data){}`.

The client side listener is simply a direct copy of the socket.io [chat](http://socket.io/get-started/chat/) demo and is confirmed to be working with the initial socket.emit at the top of the method. I think I'm missing something in my understanding on node streams (beginner project for me).

Any ideas?

**Comment by HeavyMedl** [comment]
I appreciate your kind words. Always nice to know somebody is benefiting from the work you put in.

So the default configuration for the child process (lftp) is [0,1,2] which corresponds with this:

> 'inherit' - equivalent to [process.stdin, process.stdout, process.stderr] or [0,1,2]
> [stdio options](https://nodejs.org/api/child_process.html#child_process_options_stdio)

This should be the proper setting for piping that stream to stdout. You could pass alternative configurations. For example you could write the stream to a file if you desired.

Looking at your code I see that you're actually returning a function using the `arrow` (=>) syntax. The equivalent using just _function definitions_ would look like this:

``` js
function foo(data) { 
 return function bar(data) {
  socket.emit('info', data.toString());
 }
}
```

So `bar` isn't actually being executed. Try this:

``` js
stdio : {
 stdout : data => {
  socket.emit('info', data.toString());
 }
}
// Or disregard the arrow and just use an anonymous function definition
stdio : {
 stdout : function(data) {
  socket.emit('info', data.toString());
 }
}
```

**Comment by QuirkyTurtle94** [comment]
Thank you for the help, though nothing inside the function is still executing with either method you've suggested. 

If I were to be using child_process directly I'd write something like this

``` javascript
var myProcess = require('child_process');

myProcess.spawn('ls', ['-l'], [0,1,2]); //perform 'ls -l' in the terminal

myProcess.stdout.on('data', (data) => {
  socket.emit('info', `${data}`);
});
```

And when I test this it executes correctly and the output from ls -l is produced on the client interface through socket.io's `emit()` method identified by the 'info' id. My assumption with your stdio config is that anything placed where the comment is below will act in the same way as where `socket.emit('info', '${data}');` is placed above, though in this case it's not. Am I missing something? 

``` javascript
stdio : {
 stdout : function(data) {
  //Methods placed here
 }
}
```

I think I need to read up more about how node works, rusty client side javascript knowledge doesn't seem to be enough. Do you recommend any good learning resources for this? Sorry and thank you for taking up so much of your time!

**Comment by HeavyMedl** [comment]
I'll take a peek at this when I get home. That should have worked.

**Comment by HeavyMedl** [comment]
Hey @ElliotGraham94,

I made some progress with this issue referencing [this](http://stackoverflow.com/questions/27786228/node-child-process-spawn-stdout-returning-as-null) post. For whatever reason, child_process.spawn returns an object with null values for `stdout` and `stderr` when you pass any file descriptor settings i.e. `{stdio:[0,1,2]}` like so:

``` js
spawn('lftp', ['-c', commands], {stdio:[0,1,2]});
```

Consequently, the event listeners (your functions) can't bind to `stdout` or `stderr`. I should have a fix for this in a day or two when I'm back in Seattle.

**Comment by QuirkyTurtle94** [comment]
@kurtlocker Any progress? I've been looking through the source for [node-ftps](https://github.com/Atinux/node-ftps) and when I use that, the `socket.emit()` function works just fine, though there is very little console output (your wrapper provides much nicer feedback and seems to run a lot better for sftp).

EDIT - I've accidentally closed this issue, sorry newbie to GitHub!

**Comment by HeavyMedl** [comment]
Hey @ElliotGraham94, 

I did narrow down the issue but haven't had a chance to fix it. My wife and I just moved so we've been busy. I should have something for you today.

**Comment by HeavyMedl** [comment]
Hey @ElliotGraham94,
This issue is resolved. I do want to break down what to expect with the following use case:

``` js
// client.js
const RemoteSync = require('remote-sync');
const config = {
    operations : [
        {
            operation : 'List',
            command : 'nlist files',
            settings : {
                stdio : {
                    stdout : data => {
                        console.log(data);
                    }
                }
            }
        },
        {
            operation : 'List 2',
            command : 'nlist files'
        }
    ],
    user : 'kurt',
    pw : 'pw',
    host : 'ftp.host.com',
    stdio : {
        stdout : data => {
            console.log(data);
        }
    }
};
const client = new RemoteSync(config);
client.perform(); // Returns a remote listing of files at ftp.host.com/files/
```

Here we open two separate connections to the same host, `ftp.host.com`, and execute two operations synchronously. Note that if you define `stdio` on the constructor object, it will be applied to every operation unless there is a `stdio` property defined for a particular operation. In the above example, operation `'List'` has a custom `stdio` definition that will override what's defined on the constructor. Operation `'List 2'` will use the `stdio` defined on the constructor object.

Let me know if this works for you.

**Comment by QuirkyTurtle94** [comment]
This works great. I appreciate you putting the time into getting this resolved, thanks!
