### ISSUE TITLE
I just have code:0

### ISSUE THREAD

**Issue by bahadiremre** [kurtlocker/remote-sync#2]
Hello,
Here is my code:

const RemoteSync = require('remote-sync');
const config = {
    operations: [
        {
            operation: 'List',
            command: 'nlist'
        }
    ],
    user: 'test',
    pw: 'test',
    host: '127.0.0.1',
    port: 1234
};
const client = new RemoteSync(config);
client.perform(); 

When I run this, I just get:
RemoteSync: Attemping operation(s) 1 'List':
code: 0

What is the problem with my code? I cannot see the files on my ftp server

**Comment by HeavyMedl** [comment]
Hey @bahadiremre,

I can reproduce the issue. I'll take a look today.

**Comment by HeavyMedl** [comment]
@bahadiremre,

Please grab 1.0.3 and let me know if this works for you.
